//This file just contains this constant data structure for the reactions
//This should make expanding the project really easy as all it means I have to do is tweak the values here and they populate to the rest of the game (or at least most of the game)
//Claude generated the first draft of this structure, though I have made tweaks and edits before implementing
const REACTIONS = {
    hcl_naoh: {
        name: "Hydrochloric acid + Sodium hydroxide",
        type: "acid-base",
        description: "A neutralisation reaction between a strong acid and a strong base.",
        //Prelab generated by Claude, Update later based on prediction questions
        prelab: "Hydrochloric acid + Sodium hydroxide<br>In this experiment you will combine hydrochloric acid (HCl) and sodium hydroxide (NaOH) in aqueous solution.<br>Hydrochloric acid is a strong acid. In water it dissociates completely, releasing hydrogen ions (H⁺) and chloride ions (Cl⁻). The solution you will use is 1.0 mol/L.<br>Sodium hydroxide is a strong base. In water it also dissociates completely, releasing sodium ions (Na⁺) and hydroxide ions (OH⁻). The solution you will use is 1.0 mol/L.<br>When these two solutions are combined, the H⁺ and OH⁻ ions react directly with one another. The Na⁺ and Cl⁻ ions do not participate in the reaction — they remain in solution unchanged and are known as spectator ions.<br>The net ionic equation for this reaction is:<br><br>H⁺(aq) + OH⁻(aq) → H₂O(l)<br><br>The product is liquid water and an aqueous solution of sodium chloride (table salt).<br>Before you begin, consider: what type of reaction is this? Will energy be released or absorbed? What do you expect the pH of the product solution to be? Will any solid material form?",
        reactants: [
            { 
                name: "Hydrochloric acid", 
                symbol: "HCl", 
                state: "aqueous", 
                concentration: 1.0,
                appearance: "Clear, colorless liquid, but can yellow over time",
                pH: "~0 at 1.0 mol/L",
                hazards: ["Corrosive", "Irritant"],
                ghs: ["GHS05", "GHS07"],
                molarRatio: 1,
                color: "rgba(220,210,130,0.25)"
            },
            { 
                name: "Sodium hydroxide solution", 
                symbol: "NaOH", 
                state: "aqueous", 
                concentration: 1.0,
                appearance: "Clear, colorless liquid",
                pH: "~14 at 1.0 mol/L",
                hazards: ["Corrosive"],
                ghs: ["GHS05"],
                molarRatio: 1,
                color: "rgba(202, 202, 202, 0.25)"
            }
        ],
        products: [
            { 
                name: "Sodium chloride", 
                symbol: "NaCl",
                molarRatio: 1
            },
            { 
                name: "Water", 
                symbol: "H₂O",
                molarRatio: 1
            }
        ],
        energyChange: "exothermic",
        predictions: [
            {
                question: "Will this reaction release or absorb heat?",
                options: ["Release heat (exothermic)", "Absorb heat (endothermic)", "No energy change"],
                correct: 0
            },
            // add more later
        ],
        safety: {
            eyeAndFace: "Safety Goggles",
            hands: "Nitrile Gloves",
            body: "Lab Coat",
            foot: "Closed-toe Shoes",
            respiratory: "None"
        },
        stirNeeded: 700,
        finalColor: "rgba(202, 202, 202, 0.25)",
        reactionFinishedText: "Neutralisation complete — NaCl + H₂O produced",
        disposal: {
            liquid: "Drain Disposal",
            solid: "None",
            gaseous: "None"
        },
    },
    pb_no3_ki: {
        //populate for second reaction later
    }
};