//This file just contains this constant data structure for the reactions
//This should make expanding the project really easy as all it means I have to do is tweak the values here and they populate to the rest of the game (or at least most of the game)
//Claude generated the first draft of this structure, though I have made tweaks and edits before implementing
const REACTIONS = {
    hcl_naoh: {
        name: "Hydrochloric acid + Sodium hydroxide",
        type: "acid-base",
        description: "A neutralisation reaction between a strong acid and a strong base.",
        //Prelab generated by Claude, Update later based on prediction questions
        prelab: "Hydrochloric acid + Sodium hydroxide<br>In this experiment you will combine hydrochloric acid (HCl) and sodium hydroxide (NaOH) in aqueous solution.<br>Hydrochloric acid is a strong acid. In water it dissociates completely, releasing hydrogen ions (H⁺) and chloride ions (Cl⁻). The solution you will use is 1.0 mol/L.<br>Sodium hydroxide is a strong base. In water it also dissociates completely, releasing sodium ions (Na⁺) and hydroxide ions (OH⁻). The solution you will use is 1.0 mol/L.<br>When these two solutions are combined, the H⁺ and OH⁻ ions react directly with one another. The Na⁺ and Cl⁻ ions do not participate in the reaction — they remain in solution unchanged and are known as spectator ions.<br>The net ionic equation for this reaction is:<br><br>H⁺(aq) + OH⁻(aq) → H₂O(l)<br><br>The product is liquid water and an aqueous solution of sodium chloride (table salt).<br>Before you begin, consider: what type of reaction is this? Will energy be released or absorbed? What do you expect the pH of the product solution to be? Will any solid material form?",
        reactants: [
            { 
                name: "Hydrochloric acid", 
                symbol: "HCl", 
                state: "aqueous", 
                concentration: 1.0,
                appearance: "Clear, colorless liquid",
                pH: "~0 at 1.0 mol/L",
                hazards: ["Corrosive", "Irritant"],
                ghs: ["GHS05", "GHS07"],
                molarRatio: 1,
                color: "rgba(202, 202, 202, 0.25)"
            },
            { 
                name: "Sodium hydroxide solution", 
                symbol: "NaOH", 
                state: "aqueous", 
                concentration: 1.0,
                appearance: "Clear, colorless liquid",
                pH: "~14 at 1.0 mol/L",
                hazards: ["Corrosive"],
                ghs: ["GHS05"],
                molarRatio: 1,
                color: "rgba(202, 202, 202, 0.25)"
            }
        ],
        products: [
            { 
                name: "Sodium chloride", 
                symbol: "NaCl",
                molarRatio: 1,
                phase: "solid",
                attributes: [
                    "Appearance: Not visible in solution. Outside of solution it appears as fine white crystals",
                    "Solubility: Highly soluble — 360 g/L at room temperature",
                    "Note: Na+ and Cl- were spectator ions — they did not participate in the reaction itself",
                    "Note: To isoolate the solid NaCl, the water would need to be evaportated, which is a step not included in this experiment"
                ]
            },
            { 
                name: "Water", 
                symbol: "H2O",
                molarRatio: 1,
                phase: "liquid",
                attributes: [
                    "Appearance: Clear, colorless liquid",
                    "pH: 7 — Neutral",
                    "Formed when H+ and OH- ions combined during neutralization"
                ]
            }
        ],
        energyChange: "exothermic",
        predictions: [
            {
                question: "Will this reaction release or absorb heat?",
                options: ["Release heat (exothermic)", "Absorb heat (endothermic)", "No energy change"],
                correct: 0
            },
            {
                question: "What do you expect the pH of the product solution to be?",
                options: ["Acidic (pH below 7)", "Neutral (pH 7)", "Basic (pH above 7)"],
                correct: 1
            },
            {
                question: "Will a solid precipitate form during this reaction?",
                options: ["Yes, a solid will form", "No, all products will remain in solution"],
                correct: 1
            },
            {
                question: "Will a gas be produced during this reaction?",
                options: ["Yes, a gas will be evolved", "No, no gas will be produced"],
                correct: 1
            },
            {
                question: "What type of reaction is this?",
                options: ["Acid-base neutralisation", "Combustion", "Redox reaction", "Decomposition"],
                correct: 0
            },
            {
                question: "After the reaction, which ions will remain in solution?",
                options: [ "H⁺ and OH⁻ ions", "Na⁺ and Cl⁻ ions", "Na⁺ and OH⁻ ions", "No ions — all products are neutral molecules"],
                correct: 1
            },
        ],
        safety: {
            eyeAndFace: "Safety Goggles",
            hands: "Nitrile Gloves",
            body: "Lab Coat",
            foot: "Closed-toe Shoes",
            respiratory: "None"
        },
        stirNeeded: 700,
        finalColor: "rgba(202, 202, 202, 0.25)",
        reactionFinishedText: "Neutralisation complete — NaCl + H₂O produced",
        disposal: {
            liquid: "Drain Disposal",
            solid: "None",
            gaseous: "None"
        },
        analyze: {
            temperature: {
                product: 27.3,
                roomTemp: 20,
                note: "The product is warmer than room temperature, this indicates that energy was released during the reaction."
            },
            pH: {
                value: 7,
                color: "#4caf50",
                label: "Neutral",
                note: "A pH value of 7 indicates a neutral solution."
            },
            visual: {
                text: "Clear, colorless liquid with white crystals dissolved inside.",
                note: "No precipitates or gasses were formed. The solution did not change colors during the reaction."
            },
            conductivity: {
                level: "High",
                note: "Na+ and Cl- ions dissolved in solution can carry electric charge."
            },
            evidenceKeywords: [
                {
                    label: "temperature / heat / exothermic",
                    keywords: ["temperature", "warm", "heat", "exothermic", "energy", "27", "hotter"]
                },
                {
                    label: "pH / neutral / neutralisation",
                    keywords: ["ph", "neutral", "7", "neutrali"]
                },
                {
                    label: "conductivity / ions",
                    keywords: ["conduct", "ion", "electric", "na+", "cl-", "sodium", "chloride"]
                },
                {
                    label: "visual observation / no precipitate / no gas",
                    keywords: ["clear", "colour", "precipitate", "gas", "bubble", "visual", "appear"]
                },
                {
                    label: "new product formed / NaCl / water",
                    keywords: ["nacl", "salt", "water", "product", "formed", "h2o"]
                }
            ],
            yield: {
                errorFactor: 0.94
            }
        },
        debriefTargets: [
            "Why the reaction is exothermic and what evidence from the experiment supported this",
            "The role of the limiting reactant and how the student's volume choices affected yield",
            "The difference between spectator ions (Na⁺ and Cl⁻) and the reactive ions (H⁺ and OH⁻) that actually drove the reaction",
            "What the neutral pH result tells us about the completeness of neutralisation"
        ]
    },
    pb_no3_ki: {
        //populate for second reaction later
    }
};