//const { REACTIONS } = require('./reactions.js');
//These functions have been moved from main to here to make testing with jest easier

//function generated by claude, but I have taken the time to understand it
function calculateReaction(volumes, reactionReactants, reactionProducts) {

    // calculate moles for each reactant
    const reactionMoles = reactionReactants.map((reactant, i) => ({
        name: reactant.name,
        moles: reactant.concentration * (volumes[i]/1000),
        ratio: reactant.molarRatio
    }));

    // calculate moles divided by ratio for each — the smallest value is the limiting reactant
    const limitingValue = Math.min(...reactionMoles.map(r => r.moles / r.ratio));

    // calculate yield and excess
    return {
        reactants: reactionMoles.map(r => ({
            name: r.name,
            molesAdded: r.moles,
            molesUsed: limitingValue * r.ratio,
            molesExcess: r.moles - (limitingValue * r.ratio)
        })),
        products: reactionProducts.map(product => ({
            name: product.name,
            symbol: product.symbol,
            molesProduced: limitingValue * product.molarRatio
        }))
    };
}

//Takes in a list of answers and compares them to the correct responses
//Refactored with support from Claude to enable easier testing
function checkPPEAnswers(selected, reactionSafety) {
    let checkArray = [];
    if (selected.eye == reactionSafety.eyeAndFace.equipment) {
        checkArray.push(true);
    } else {
        checkArray.push(false);
    }
    if (selected.hands == reactionSafety.hands.equipment) {
        checkArray.push(true);
    } else {
        checkArray.push(false);
    }
    if (selected.body == reactionSafety.body.equipment) {
        checkArray.push(true);
    } else {
        checkArray.push(false);
    }
    if (selected.foot == reactionSafety.foot.equipment) {
        checkArray.push(true);
    } else {
        checkArray.push(false);
    }
    if (selected.respiratory == reactionSafety.respiratory.equipment) {
        checkArray.push(true);
    } else {
        checkArray.push(false);
    }
    return checkArray;
}

//Probably not the best way to do this, but it was the first that came to mind
function setAlpha(rgbaString, newAlpha, hasAlpha = true) {
    let channels = rgbaString.split(",");
    if (hasAlpha == true) {
        return (channels[0] + "," + channels[1] + "," + channels[2] + "," + newAlpha + ")");
    } else {
        let splitOpen = channels[0].split("(");
        let end = channels[2].replace(")", "");
        return ("rgba(" + splitOpen[1] + "," + channels[1] + "," + end[0] + "," + newAlpha + ")");
    }
}

//Averages each channel of two supplied rgba colors
function mixColors(rgbaString1, rgbaString2) {
    //If the supplied first color is actually in rgb format
    if (!rgbaString1.startsWith("rgba")) {
        //convert it to rgba with an alpha channel
        rgbaString1 = setAlpha(rgbaString1, 1, false);
    }
    //If the supplied second color is actually in rgb format
    if (!rgbaString2.startsWith("rgba")) {
        //convert it to rgba with an alpha channel
        rgbaString2 = setAlpha(rgbaString2, 1, false);
    }

    let color1 = rgbaString1.split(",");
    color1[0] = color1[0].replace("rgba(", "");
    color1[3] = color1[3].replace(")", "");
    color1 = color1.map(color => Number(color));

    let color2 = rgbaString2.split(",");
    color2[0] = color2[0].replace("rgba(", "");
    color2[3] = color2[3].replace(")", "");
    color2 = color2.map(color => Number(color));

    let avgR = (color1[0] + color2[0])/2;
    let avgG = (color1[1] + color2[1])/2;
    let avgB = (color1[2] + color2[2])/2;
    let avgA = (color1[3] + color2[3])/2;

    if (avgA == 1) {
        //Return an rgb string since the alpha channel is max
        return ("rgb(" + avgR + "," + avgG + "," + avgB + ")");
    } else {
        return ("rgba(" + avgR + "," + avgG + "," + avgB + "," + avgA + ")");
    }
}

//returns the distance between two coordinate pairs
function distance(x1, y1, x2, y2) {
    let dist = Math.hypot(x2-x1, y2-y1);
    return dist;
}

//Collects all of the relevant information from the play session to be sent as part of the AI debrief
function buildRunSummary(summaryReaction, summaryReactants, summaryProducts) {
    return {
        reactionName:      REACTIONS[summaryReaction].name,
        reactants:         summaryReactants.map(r => r.name + " (" + r.symbol + ")"),
        products:          summaryProducts.map(p => p.name + " (" + p.symbol + ")"),
        energyChange:      REACTIONS[summaryReaction].energyChange,
        yieldPercent:      yieldPercent,
        evidenceStatement: evidenceStatement,
        predictions:       predictions.map((p, i) => ({
            question:      p.question,
            studentAnswer: playerPredictions[i] || "No answer recorded",
            correctAnswer: p.options[p.correct],
            correct:       playerPredictions[i] === p.options[p.correct]
        })),
        debriefTargets: REACTIONS[summaryReaction].debriefTargets,
        volumes: summaryReactants.map((r, i) => ({
            name:          r.name,
            symbol:        r.symbol,
            volumeML:      volumes[i],
            molesAdded:    moles.reactants[i].molesAdded,
            molesExcess:   moles.reactants[i].molesExcess,
            isLimiting:    moles.reactants[i].molesExcess === 0
        })),
        equationBalanced: moles.reactants.every(r => r.molesExcess < 0.001)
    };
}

//Builds the full system prompt from the runSummary object
function buildSystemPrompt(summary) {
    const predictionLines = summary.predictions.map(p =>
        `  Q: "${p.question}"\n  Student answered: "${p.studentAnswer}" — ${p.correct
            ? "Correct"
            : "Incorrect (correct answer: " + p.correctAnswer + ")"}`
    ).join("\n");

    const yieldLabel = summary.yieldPercent >= 90
        ? "this is an excellent yield, treat it as a success and do not question it"
        : summary.yieldPercent >= 80
        ? "this is an acceptable yield for a teaching lab"
        : "this yield is lower than expected and worth discussing";

    const learningTargets = summary.debriefTargets.map((target, i) =>
        `${i + 1}. ${target}`
    ).join("\n");

    const yieldNote = summary.yieldPercent < 80
        ? `\nYield note: the student's yield of ${summary.yieldPercent}% is lower than expected and worth discussing.`
        : summary.yieldPercent >= 90
        ? `\nYield note: the student's yield of ${summary.yieldPercent}% is excellent. Praise it and do not treat it as a problem.`
        : `\nYield note: the student's yield of ${summary.yieldPercent}% is acceptable for a teaching lab.`;

    const volumeLines = summary.volumes.map(v =>
        `  ${v.name}: ${v.volumeML}mL (${v.molesAdded.toFixed(3)} mol) — ${v.isLimiting
        ? "limiting reactant"
        : `excess by ${v.molesExcess.toFixed(3)} mol`}`
    ).join("\n");

const balanceNote = summary.equationBalanced
    ? "The student balanced the equation correctly — both reactants were fully consumed."
    : "The student did not balance the equation — one reactant was in excess and was wasted.";
    return `You are a Socratic chemistry tutor debriefing a student who has just completed a virtual lab experiment. Your role is to deepen their understanding through questions, not to lecture or provide answers directly.

EXPERIMENT CONTEXT:
- Reaction performed: ${summary.reactionName}
- Reactants: ${summary.reactants.join(", ")}
- Products: ${summary.products.join(", ")}
- Energy change: ${summary.energyChange}

STUDENT PERFORMANCE:
- Predictions made before the experiment:
${predictionLines}
- Yield achieved: ${summary.yieldPercent}% — ${yieldLabel}
- Evidence statement written by the student: "${summary.evidenceStatement}"
- Volumes used: ${volumeLines}
- Stoichiometry: ${balanceNote}

YOUR BEHAVIOUR RULES:
1. Never give answers directly. Always respond with a question or a prompt that guides the student toward the answer themselves.
2. Ask only one question at a time. Wait for the student to respond before moving on.
3. Start with what the student got right or noticed themselves before addressing gaps.
4. When a student gives a wrong answer, do not say "wrong" or "incorrect". Instead ask a follow-up that exposes the flaw in their reasoning.
5. Target the student's specific wrong predictions first.
6. Keep your responses short — two to four sentences maximum. This is a conversation, not a lecture.
7. Use plain language. Introduce technical terms only after the student has demonstrated the underlying concept in their own words.
8. After covering the key learning targets, offer a brief closing summary of what the student demonstrated, then tell them they have completed the debrief.
9. A yield above 90% is considered excellent in a teaching lab. If the student achieved this, acknowledge it as a success and do not treat it as a problem to investigate. Only explore yield as a learning topic if it fell below 80%.

UNIVERSAL LEARNING TARGETS (apply to every reaction — cover these alongside the reaction-specific targets):
- The role of the limiting reactant and how the student's volume choices affected yield
- Why yield is rarely 100% in a real experiment — only raise this if yield was below 80%. A yield above 90% should be praised, not questioned.
${yieldNote}

REACTION-SPECIFIC LEARNING TARGETS (cover in order of priority):
${learningTargets}

OPENING MESSAGE:
Begin by acknowledging one specific thing from the student's evidence statement, then ask one open question about it. Do not summarise the experiment back to them. Get straight into the discussion.`;
}

//exports the functions for use in testing
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        calculateReaction,
        checkPPEAnswers,
        setAlpha,
        mixColors,
        distance,
        buildRunSummary,
        buildSystemPrompt
    };
}